# Generated by Django 3.1.7 on 2021-03-26 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('045a0d3c-9678-41e1-8587-c07f98e6317c'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('85790bc2-7623-4213-8c83-8812b3f6e9c1'), primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0f1bf4d4-981c-4ef9-bd93-cb7a400cd7ed'), primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionTerritorial',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d30e68af-fbea-42ea-beea-5a81c225d31f'), primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Divisiones territoriales',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('961b50e6-95c1-4d94-9c52-7aec8ec0771f'), editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=10, unique=True)),
                ('razon_social', models.CharField(max_length=30)),
                ('fecha_formalizacion', models.CharField(max_length=30)),
                ('cubrimiento', models.CharField(max_length=1)),
                ('cantidad_empleados', models.PositiveIntegerField(default=0)),
                ('productos', models.CharField(max_length=1000, null=True)),
                ('servicios', models.CharField(max_length=1000, null=True)),
                ('actividad_economica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.actividadeconomica')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaProyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6c106d06-ef08-4017-9408-e0a0641e6005'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('929c7d0f-1608-49a5-94a4-a32f65dfe38c'), primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEstudio',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a6e4e964-1490-4d6e-9b3c-ab520513075b'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('10cce1c7-8fac-4780-ab0a-8562c3cf925f'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b8f917d2-1980-4ef5-91ad-40bf1ba95aeb'), primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d31ae251-6fc3-4df5-a35a-7e9c8f0341da'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoEmpresarial',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5f215cbc-9106-48c2-a4c4-6138d08fe2ec'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('facturacion_mensual_aprox', models.PositiveIntegerField(default=0)),
                ('tipo_mercado', models.CharField(max_length=5, null=True)),
                ('numero_integrantes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(3)])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decore.empresa')),
                ('etapa_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.etapaproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TamañoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c5633d90-d686-48b9-aa30-e35c829099a2'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSociedad',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('632187d7-2048-4024-8704-ecd7620054f4'), editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloNegocio',
            fields=[
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='decore.empresa')),
                ('quien_ayudara', models.CharField(max_length=1000)),
                ('como_hace', models.CharField(max_length=1000)),
                ('que_haces', models.CharField(max_length=1000)),
                ('como_interactuas', models.CharField(max_length=1000)),
                ('a_quien_ayudas', models.CharField(max_length=1000)),
                ('que_necesitas', models.CharField(max_length=1000)),
                ('como_alcanzarlos', models.CharField(max_length=1000)),
                ('cual_sera_costo', models.CharField(max_length=1000)),
                ('cuanto_ganaras', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b0244f19-4864-47d1-a153-46212f799f87'), editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('sexo', models.CharField(max_length=2)),
                ('es_lider', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decore.empresa')),
                ('nivel_estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.nivelestudio')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.ocupacion')),
                ('profesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.profesion')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamaño_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.tamañoempresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_sociedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.tiposociedad'),
        ),
        migrations.CreateModel(
            name='ProyectoEmpresarialIntegrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decore.integrante')),
                ('proyecto_empresarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decore.proyectoempresarial')),
            ],
            options={
                'unique_together': {('proyecto_empresarial', 'integrante')},
            },
        ),
        migrations.CreateModel(
            name='InformacionContactoEmpresa',
            fields=[
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='decore.empresa')),
                ('celular', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('celular2', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('telefono', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(6)])),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Email invalid')])),
                ('instagram', models.URLField(unique=True, validators=[django.core.validators.URLValidator()])),
                ('facebook', models.URLField(unique=True, validators=[django.core.validators.URLValidator()])),
                ('otro_barrio', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('barrio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.barrio')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.departamento')),
                ('division_territorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.divisionterritorial')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.municipio')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decore.pais')),
            ],
        ),
        migrations.AddIndex(
            model_name='informacioncontactoempresa',
            index=models.Index(fields=['celular'], name='celular_idx'),
        ),
        migrations.AddIndex(
            model_name='informacioncontactoempresa',
            index=models.Index(fields=['celular2'], name='celular2_idx'),
        ),
        migrations.AddIndex(
            model_name='informacioncontactoempresa',
            index=models.Index(fields=['telefono'], name='telefono_idx'),
        ),
        migrations.AddIndex(
            model_name='informacioncontactoempresa',
            index=models.Index(fields=['correo_electronico'], name='correo_electronico_idx'),
        ),
    ]
