# Generated by Django 3.1.7 on 2021-03-26 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('decore', '0002_auto_20210326_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadeconomica',
            options={'verbose_name_plural': 'Actividades económicas'},
        ),
        migrations.AlterModelOptions(
            name='tamanioempresa',
            options={'verbose_name_plural': 'Tamaño de empresas'},
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68861394-5d29-4de5-bdd5-fa0d6f2c6b8a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9142c1a-34d2-4d4a-8154-387d28733bf2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7dd8c795-0122-46a7-8947-3097152aea8c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='divisionterritorial',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1162b35-3400-4631-8d2d-9df5fb478936'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cd1d876-8416-4298-a0f9-108351df4c1c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etapaproyecto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80cec07f-3d93-42ce-ae33-705e4a3da45b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf0fe827-1555-4f0f-9633-cbb2f0b06045'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('200cd8d5-2bc3-4fd9-9925-71c9d571a522'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nivelestudio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aafd9bda-b768-4dc2-a18e-35e4f35e4752'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('805fda42-087a-4c6e-a410-e078c449e9ad'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.UUIDField(default=uuid.UUID('891b355d-d190-4f07-a941-f700a65c8cd9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d169542e-348d-476a-84e9-84276e54f8b4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e273b90d-8573-477c-a2f1-88b8db6450fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tamanioempresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('58a1508f-1edc-45da-bcc0-baae57654549'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposociedad',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1165f901-faac-4c9e-9248-4ba88e235f95'), primary_key=True, serialize=False),
        ),
    ]
