# Generated by Django 3.1.7 on 2021-03-28 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('decore', '0003_auto_20210326_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelestudio',
            options={'verbose_name_plural': 'Niveles de estudio'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='tiposociedad',
            options={'verbose_name_plural': 'Tipos de sociedades'},
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cae4042-5a72-4ce1-8d72-e1118360e0eb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f74c4b84-8c76-4545-9382-2444fcb85941'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.UUIDField(default=uuid.UUID('147fecd4-7642-4861-b733-6212ee543452'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='divisionterritorial',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb7004ad-8dd0-4d6b-9fd8-59893b0bf62a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_formalizacion',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dcb7bc7-9ec6-472e-87b2-b252754afa4c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etapaproyecto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25174db8-6351-4f12-8c35-b92c2f26b573'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b21a0cf-6359-4dbd-9447-ebfd161fe09f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5980e248-0c45-4dc1-97f1-f7450d13f509'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nivelestudio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39c31b18-a1df-4f71-a0d4-cd6af6dbb8ca'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ebfdd2a0-a063-4e5d-91b8-390921124744'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id',
            field=models.UUIDField(default=uuid.UUID('321f35ad-84bc-4a1b-9fd3-ea28f5eb7f48'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8656870-cce8-4c09-bf25-54458a9962de'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa8c5b86-3c93-408e-9ca4-658fb37b7fe5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tamanioempresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37fd6296-b27f-4102-8e86-01bf7730195d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposociedad',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7c07fc8-195e-4976-b3e4-32cc946f2d61'), primary_key=True, serialize=False),
        ),
    ]
